import isSolved from "../index";

it("should return correct result", () => {
	const grid = [
		[
			{ value: 9, changeable: false, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 7, changeable: false, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
			{ value: 5, changeable: true, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
		],
		[
			{ value: 2, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
		],
		[
			{ value: 4, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
		],
		[
			{ value: 3, changeable: false, candidates: [] },
			{ value: 5, changeable: true, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 7, changeable: false, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 2, changeable: false, candidates: [] },
			{ value: 9, changeable: true, candidates: [] },
		],
		[
			{ value: 1, changeable: false, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
			{ value: 2, changeable: false, candidates: [] },
			{ value: 9, changeable: true, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 7, changeable: false, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 5, changeable: true, candidates: [] },
		],
		[
			{ value: 7, changeable: true, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
		],
		[
			{ value: 6, changeable: true, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
			{ value: 1, changeable: false, candidates: [] },
		],
		[
			{ value: 8, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
		],
		[
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: null, changeable: true, candidates: [] },
			{ value: 2, changeable: false, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
		],
	];

	expect(isSolved(grid)).toBe(false);

	const solvedGrid = [
		[
			{ value: 9, changeable: false, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 7, changeable: false, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
			{ value: 5, changeable: true, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
		],
		[
			{ value: 2, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
		],
		[
			{ value: 4, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
		],
		[
			{ value: 3, changeable: false, candidates: [] },
			{ value: 5, changeable: true, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 7, changeable: false, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 2, changeable: false, candidates: [] },
			{ value: 9, changeable: true, candidates: [] },
		],
		[
			{ value: 1, changeable: false, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
			{ value: 2, changeable: false, candidates: [] },
			{ value: 9, changeable: true, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 7, changeable: false, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 5, changeable: true, candidates: [] },
		],
		[
			{ value: 7, changeable: true, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
		],
		[
			{ value: 6, changeable: true, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 8, changeable: false, candidates: [] },
			{ value: 1, changeable: false, candidates: [] },
		],
		[
			{ value: 8, changeable: true, candidates: [] },
			{ value: 9, changeable: false, candidates: [] },
			{ value: 2, changeable: true, candidates: [] },
			{ value: 6, changeable: false, candidates: [] },
			{ value: 4, changeable: false, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 3, changeable: true, candidates: [] },
			{ value: 5, changeable: false, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
		],
		[
			{ value: 5, changeable: false, candidates: [] },
			{ value: 3, changeable: false, candidates: [] },
			{ value: 1, changeable: true, candidates: [] },
			{ value: 7, changeable: true, candidates: [] },
			{ value: 8, changeable: true, candidates: [] },
			{ value: 9, changeable: true, candidates: [] },
			{ value: 2, changeable: false, candidates: [] },
			{ value: 6, changeable: true, candidates: [] },
			{ value: 4, changeable: true, candidates: [] },
		],
	];

	expect(isSolved(solvedGrid)).toBe(true);
});
